services:
  postgres:
    container_name: postgres-db
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT}:5432"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    networks:
      - postgres-network

volumes:
  pgdata:

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

networks:
  postgres-network:
    external: true